<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-142469963-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-142469963-1', { 'optimize_id': 'GTM-PSQ6JK2'});
    </script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PVFZMDR');</script>
    <!-- End Google Tag Manager -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Best Resort To enjoy the warmth of THE GREAT RANN OF KUTCH. we help customers focus on enjoying RANN and craft experience that is unique and memorable.">
    <meta name="Dev" content="Laxit-Patel">
    <meta name="Author" content="Vijay-Soni">
    <meta name="Keywords" content="star resort, rann utsav, star resort kutch, gorevali, rann utsav bookin, bhunga, rajwadi bhunga, kutchi bhunga">
    <meta property="og:title" content="Star Resort Kutch - Best Staying Solutions in Rann Of Kutch">
    <meta property="og:site_name" content="Star Resort Kutch">
    <meta property="og:url" content="http://starresortkutch.com">
    <meta property="og:description" content="Best Resort To enjoy the warmth of THE GREAT RANN OF KUTCH. we help customers focus on enjoying RANN and craft experience that is unique and memorable.">
    <meta property="og:type" content="website">
    <meta property="og:image" content="http://www.starresortkutch.com/assets/img/gallery/Bhunga.jpg">
    <link rel="canonical" href="index.php" />
    <link rel="alternate" href="http://starresortkutch.com" hreflang="en-in" />
    <link rel="next" href="http://starresortkutch/assets/modules/sendmail.php" />
    <link rel="apple-touch-icon" href="apple-touch-iphone.png" />
    <link rel="apple-touch-icon" sizes="72x72" href="apple-touch-ipad.png" />
    <link rel="apple-touch-icon" sizes="114x114" href="apple-touch-iphone4.png" />
    <link rel="apple-touch-icon" sizes="144x144" href="apple-touch-ipad-retina.png" />
    <title>Gallery - Star Resort Kutch - Best Staying Solutions in Rann Of Kutch</title>

    <?php include 'assets/modules/includes/primary-stylesheet.php';?>

</head>
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "Restaurant",
        "name" : "Star Resort Kutch",
        "image" : "http://starresortkutch.com/assets/img/gallery/Bhunga.jpg",
        "telephone" : "+91-9898629858",
        "email" : "kutchhotelsbooking@gmail.com",
        "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "Manglam Was Gorewali,Kutch,Gujarat-India"
        }
    }
</script>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVFZMDR"
                  height="0" width="0" class="hidden-tag"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.3&appId=287626901730305&autoLogAppEvents=1"></script>


<?php include("assets/modules/includes/header-global.php"); ?>

<main>
    <div class="position-relative">
        <!-- shape Hero -->
        <section class="section section-lg section-shaped pb-250 main-bg-gallery ">
            <div class="shape shape-style-1 shape-default">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="container py-lg-md d-flex">
                <div class="col px-0">
                    <div class="row">
                        <div class="col-lg-12 ">
                            <ul class="nav nav-pills nav-pills-circle mb-3"  role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link rounded-circle active pulser " id="home-tab"  href="index.php" >
                                        <span class="nav-link-icon d-block"><i class="fa fa-home"></i></span>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link bg-transparent shadow-none"   href="#"  aria-selected="false">
                                        <span class="nav-link-icon d-block"><i class="fa fa-arrow-right text-white"></i></span>
                                    </a>
                                </li>
                                <li class="nav-item ">
                                    <a class="" id="contact-tab"  href="gallery.php"  aria-selected="true">
                                        <h1 class=" text-white "><b>Gallery</b></h1>
                                    </a>
                                </li>
                            </ul>


                        </div>
                    </div>
                </div>
            </div>
            <!-- SVG separator -->
            <div class="separator separator-bottom separator-skew">
                <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
                    <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
                </svg>
            </div>
        </section>
        <!-- 1st Hero Variation -->
    </div>
    <section class="section section-lg pt-lg-0 mt--300">
        <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-lg-12">

                        <div class="masonry-wrapper">
                            <div class="masonry">
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-1.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-1.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-2.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-2.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-3.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-3.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-4.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-4.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-5.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-5.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-6.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-6.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-7.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-7.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-8.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-h-8.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow">
                                    <img src="assets/img/gallery/gal-v-9.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>
                                <div class="masonry-item dense-shadow mb-3">
                                    <img src="assets/img/gallery/gal-h-9.jpg" alt="Dummy Image" width="150%" class="masonry-content">
                                </div>


                            </div>
                        </div>

                    </div>
                </div>
        </div>
    </section>

</main>

<?php  include("assets/modules/includes/main-footer.php"); ?>
<!-- Core -->
<script src="./assets/vendor/jquery/jquery.min.js"></script>
<script src="./assets/vendor/popper/popper.min.js"></script>
<script src="./assets/vendor/bootstrap/bootstrap.min.js"></script>
<script src="./assets/vendor/headroom/headroom.min.js"></script>
<!-- Argon JS -->
<script src="./assets/js/argon.js?v=1.0.1"></script>
<!-- Date Picker -->
<script src="./assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<!-- country Dropdown-->
<script src="//geodata.solutions/includes/countrystatecity.js"></script>
<!-- form validator -->
<script scr="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>
<!-- copy-to-clipboard -->
<script>

    function copyToClipboardDeluxe(id) {
        var from = document.getElementById(id);
        var range = document.createRange();
        window.getSelection().removeAllRanges();
        range.selectNode(from);
        window.getSelection().addRange(range);
        document.execCommand('copy');
        window.getSelection().removeAllRanges();
        var btn = document.getElementById("copyToClipboardButtonDeluxe");
        btn.innerHTML = "Copied!!!";
    }

</script>
<!-- initiate validators-->
<script>
    $("#book-now-form").validate();
</script>
</body>

</html>